# Site settings
remote_theme: JeremySkinner/PrettyDocs-theme
url: https://leakyabstractions.github.io
title: &site_title FluentValidation
branding:
  highlight: Fluent
  bold: Validation

# Owner
owner:
  name: Jeremy Skinner
  twitter: &site_owner_twitter JeremySkinner
  copyright:
    author: "[Jeremy Skinner](http://jeremyskinner.co.uk/)"

# Google Analytics
google_analytics: UA-884625-14

# Collections
collections:
  doc:
    output: true
    permalink: /:path

# Default values
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
