name: CI

on:
  push:
    branches:
    - main
    - 9.x
    - 10.x
  pull_request:
    branches:
      - main
      - 9.x
      - 10.x
      - 11.x

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-2019', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get SDKs to install
      shell: pwsh
      # Collect the SDKs we need by parsing global.json
      # Supplementary sdks are stored in an "others" array.
      run: |
        $json = ConvertFrom-Json (Get-Content global.json -Raw)
        $sdks = ($json.others + $json.sdk.version) -join ","
        echo "REQUIRED_SDKS=$sdks" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install .NET SDKs
      uses: JeremySkinner/global-json-dotnet-install@master
      with:
        versions: ${{ env.REQUIRED_SDKS }}

    - name: Build and Test
      run: ./build.ps1
      shell: pwsh
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
