name: Release

#on:
#  push:
#    tags:
#    - '*.*.*'

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: 'windows-2019'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get SDKs to install
      shell: pwsh
      # Collect the SDKs we need by parsing global.json
      # Supplementary sdks are stored in an "others" array.
      run: |
        $json = ConvertFrom-Json (Get-Content global.json -Raw)
        $sdks = ($json.others + $json.sdk.version) -join ","
        Write-Output "::set-env name=REQUIRED_SDKS::$sdks"

    # Official actions/setup-dotnet doesn't support multiple side-by-side SDK installation.
    # Remove workaround once https://github.com/actions/setup-dotnet/issues/25 is fixed

    # - name: Install .NET SDKs
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ env.REQUIRED_SDKS }}

    - name: Install .NET SDKs
      uses: JeremySkinner/global-json-dotnet-install@master
      with:
        versions: ${{ env.REQUIRED_SDKS }}

    - name: Build and Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      run: ./build.ps1 -t compile,test,deploy,publish-ci
      shell: pwsh
